#!/bin/sh

rm -f Makefile.def

echo 'docdir = ${prefix}/share/Mylib-C/doc' >> Makefile.def
echo 'MYLIB = ${top_srcdir}/mylib' >> Makefile.def
echo 'UNITTESTS = ${top_srcdir}/unit-tests' >> Makefile.def
echo 'EXAMPLES = ${top_srcdir}/examples' >> Makefile.def
echo '' >> Makefile.def

MYLIBMODULES='addsrt bitmatrix bitset bitvector chrono gdef mystr num num2 tables tcode util rngstream'

UNITTESTSMODULES='unit num_utest num2_utest bitvector_utest bitmatrix_utest rngstream_utest bitset_utest'

EXAMPLESMODULES='bitvector_example bitmatrix_example'

function writevar() {
   HEADERS=""
   TEX=""
   SOURCES=""
   for mod in $1; do
      HEADERS="$HEADERS ${mod}.h"
      SOURCES="$SOURCES ${mod}.c"
      TEX="$TEX \$($2)/${mod}.tex"
   done
   echo "$2HEADERS =$HEADERS" >> Makefile.def
   echo "$2SOURCES =$SOURCES" >> Makefile.def
   echo "$2TEX =$TEX" >> Makefile.def
   echo '' >> Makefile.def
   unset HEADERS
   unset TEX
   unset SOURCES
}

writevar "$MYLIBMODULES" 'MYLIB'
writevar "$UNITTESTSMODULES" "UNITTESTS"
writevar "$EXAMPLESMODULES" "EXAMPLES"


unset writevar
unset MYLIBMODULES
unset UNITTESTSMODULES
unset EXAMPLES
