docdir = ${prefix}/share/Mylib-C/doc
MYLIB = ${top_srcdir}/mylib
UNITTESTS = ${top_srcdir}/unit-tests
EXAMPLES = ${top_srcdir}/examples

MYLIBHEADERS = gdef.h addstr.h bitset.h chrono.h mystr.h num.h num2.h tables.h util.h
MYLIBSOURCES = gdef.c addstr.c bitset.c chrono.c mystr.c num.c num2.c tables.c util.c
MYLIBTEX = $(MYLIB)/gdef.tex $(MYLIB)/addstr.tex $(MYLIB)/bitset.tex $(MYLIB)/chrono.tex $(MYLIB)/mystr.tex $(MYLIB)/num.tex $(MYLIB)/num2.tex $(MYLIB)/tables.tex $(MYLIB)/util.tex

UNITTESTSHEADERS = unit.h num_utest.h num2_utest.h
UNITTESTSSOURCES = unit.c num_utest.c num2_utest.c
UNITTESTSTEX = $(UNITTESTS)/unit.tex $(UNITTESTS)/num_utest.tex $(UNITTESTS)/num2_utest.tex

EXAMPLESSOURCES = bitvector_example.c bitmatrix_example.c
